// This file is normally regenerated by `npm run cf-typegen` (wrangler types).
// A hand-written baseline is kept here so the project type-checks before
// `wrangler` has been run against a real Cloudflare account.
interface CloudflareEnv {
  ASSETS: Fetcher;
  LEAD_RATE_LIMITER: { limit: (options: { key: string }) => Promise<{ success: boolean }> };

  GHL_MODE: string;

  // Secrets - set with `wrangler secret put NAME`, or in `.dev.vars` locally.
  RESEND_API_KEY?: string;
  LEAD_EMAIL_TO?: string;
  LEAD_EMAIL_FROM?: string;

  GHL_INBOUND_WEBHOOK_URL?: string;
  GHL_API_BASE?: string;
  GHL_API_TOKEN?: string;
  GHL_LOCATION_ID?: string;
  GHL_PIPELINE_ID?: string;
  GHL_PIPELINE_STAGE_ID?: string;

  LEAD_WEBHOOK_URL?: string;

  TURNSTILE_SECRET_KEY?: string;
}
